const { FlatCompat } = require('@eslint/eslintrc');
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: {},
});

module.exports = [
  ...compat.extends(
    'eslint:recommended',
    'plugin:prettier/recommended',
    'plugin:react/recommended',
    'plugin:react/jsx-runtime',
    'prettier',
  ),
  {
    languageOptions: {
      globals: {
        browser: 'readonly',
        node: 'readonly',
        es2021: 'readonly',
      },
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      react: require('eslint-plugin-react'),
      import: require('eslint-plugin-import'),
      prettier: require('eslint-plugin-prettier'),
    },
    settings: {
      'import/resolver': {
        alias: {
          map: [
            ['@', './src'],
            ['@/components', './src/components'],
            ['@/config', './src/config'],
            ['@/container', './src/container'],
            ['@/demoData', './src/demoData'],
            ['@/i18n', './src/i18n'],
            ['@/layout', './src/layout'],
            ['@/pages', './src/pages'],
            ['@/redux', './src/redux'],
            ['@/routes', './src/routes'],
            ['@/static', './src/static'],
            ['@/utils', './src/utils'],
            ['@/mock', './src/mock'],
          ],
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        },
      },
    },
    rules: {
      'prettier/prettier': 'error',
      'import/no-named-as-default-member': 0,
      'react/jsx-filename-extension': [0, { extensions: ['.js', '.jsx'] }],
      'import/prefer-default-export': 0,
      'import/no-extraneous-dependencies': 0,
      'jsx-a11y/anchor-is-valid': 0,
      'react/jsx-props-no-spreading': 0,
      'react/forbid-prop-types': 0,
      'react/require-default-props': 0,
      'no-nested-ternary': 0,
      'global-require': 0,
      'import/no-dynamic-require': 0,
      'react/no-array-index-key': 0,
      'default-param-last': 0,
      'react/no-unstable-nested-components': 0,
      'no-param-reassign': 0,
      'react/jsx-no-useless-fragment': 0,
      'react/react-in-jsx-scope': 0,
      'react/jsx-no-bind': 0,
      radix: 0,
      'consistent-return': 0,
      'no-alert': 0,
      'func-names': 0,
      'no-unused-vars': ['warn', { vars: 'all', args: 'none', ignoreRestSiblings: false }],
      'jsx-a11y/img-redundant-alt': 'off',
      'no-console': 0,
      'react/prop-types': 'off',
      'import/order': 'off',
      'react/function-component-definition': 'off',
      'no-underscore-dangle': 'off',
      camelcase: 'off',
      'no-shadow': 'off',
      'react/jsx-fragments': 'off',
      'import/extensions': 'off',
      'no-unused-expressions': 1,
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'react/display-name': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'arrow-parens': ['error', 'always'],
      'comma-dangle': ['error', 'always-multiline'],
    },
    ignores: [
      'node_modules/**',
      'build/**',
      'public/**',
      'src/serviceWorker.js',
      'jsconfig.json',
      '**/*.json',
      'style.js',
      'Style.js',
      '.eslintrc',
    ],
  },
];
