export const inbox = [
  {
    userId: 1,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'name123@example.com',
    to: 'me',
    img: 'static/img/users/1.png',
    id: 1585118055048,
    subject: 'Email subject lorem ipsum',
    attach: [],
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    date: '2024-07-01',
  },
  {
    userId: 2,
    status: 'read',
    type: 'inbox',
    stared: true,
    from: 'another@example.com',
    to: 'me',
    img: 'static/img/users/2.png',
    id: 1585118055049,
    subject: 'Another email subject',
    attach: [],
    body: 'Another email body text here.',
    date: '2024-07-02',
  },
  {
    userId: 3,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'jane.doe@example.com',
    to: 'me',
    img: 'static/img/users/3.png',
    id: 1585118055054,
    subject: 'Welcome to our service',
    attach: [],
    body: 'Dear John Doe, welcome to our service! We hope you find everything you need. If you have any questions, feel free to reach out to us.',
    date: '2024-07-03',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'support@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055055,
    subject: 'Support Ticket Update',
    attach: [],
    body: 'Hello Jane Smith, your support ticket has been updated. Please check your ticket for more details.',
    date: '2024-07-04',
  },
  {
    userId: 3,
    status: 'read',
    type: 'inbox',
    stared: true,
    from: 'newsletter@example.com',
    to: 'me',
    img: 'static/img/users/3.png',
    id: 1585118055056,
    subject: 'Monthly Newsletter',
    attach: [],
    body: 'Hi John Doe, here is your monthly newsletter with updates and news.',
    date: '2024-07-05',
  },
  {
    userId: 4,
    status: 'read',
    type: 'inbox',
    stared: false,
    from: 'admin@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055057,
    subject: 'Account Verification',
    attach: [],
    body: 'Dear Jane Smith, please verify your account using the link provided.',
    date: '2024-07-06',
  },
];
