export const inbox = [
  {
    userId: 1,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'name123@example.com',
    to: 'me',
    img: 'static/img/users/1.png',
    id: 1585118055048,
    subject: 'Email subject lorem ipsum',
    attach: [],
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    date: '2024-07-01',
  },
  {
    userId: 2,
    status: 'read',
    type: 'inbox',
    stared: true,
    from: 'another@example.com',
    to: 'me',
    img: 'static/img/users/2.png',
    id: 1585118055049,
    subject: 'Another email subject',
    attach: [],
    body: 'Another email body text here.',
    date: '2024-07-02',
  },
  {
    userId: 3,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'jane.doe@example.com',
    to: 'me',
    img: 'static/img/users/3.png',
    id: 1585118055054,
    subject: 'Welcome to our service',
    attach: [],
    body: 'Dear John Doe, welcome to our service! We hope you find everything you need. If you have any questions, feel free to reach out to us.',
    date: '2024-07-03',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'support@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055055,
    subject: 'Support Ticket Update',
    attach: [],
    body: 'Hello Jane Smith, your support ticket has been updated. Please check your ticket for more details.',
    date: '2024-07-04',
  },
  {
    userId: 3,
    status: 'read',
    type: 'inbox',
    stared: true,
    from: 'newsletter@example.com',
    to: 'me',
    img: 'static/img/users/3.png',
    id: 1585118055056,
    subject: 'Monthly Newsletter',
    attach: [],
    body: 'Hi John Doe, here is your monthly newsletter with updates and news.',
    date: '2024-07-05',
  },
  {
    userId: 4,
    status: 'read',
    type: 'inbox',
    stared: false,
    from: 'admin@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055057,
    subject: 'Account Verification',
    attach: [],
    body: 'Dear Jane Smith, please verify your account using the link provided.',
    date: '2024-07-06',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'newsletter@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055058,
    subject: 'Special Offers for You',
    attach: [],
    body: 'Hello Jane Smith, we have some special offers just for you. Check them out and save big!',
    date: '2024-07-07',
  },
  {
    userId: 4,
    status: 'read',
    type: 'inbox',
    stared: false,
    from: 'service@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055059,
    subject: 'Service Announcement',
    attach: [],
    body: 'Dear Jane, we are making some updates to our service. Please be aware of the changes.',
    date: '2024-07-08',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: true,
    from: 'contact@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055060,
    subject: 'New Contact Request',
    attach: [],
    body: 'Hello Jane Smith, you have a new contact request. Check your contacts to respond.',
    date: '2024-07-09',
  },
  {
    userId: 4,
    status: 'read',
    type: 'inbox',
    stared: false,
    from: 'promotion@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055061,
    subject: 'Exciting New Promotions',
    attach: [],
    body: 'Hi Jane, check out our exciting new promotions and discounts for this month.',
    date: '2024-07-10',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'feedback@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055062,
    subject: 'We Value Your Feedback',
    attach: [],
    body: 'Dear Jane Smith, we would love to hear your feedback on our services.',
    date: '2024-07-11',
  },
  {
    userId: 4,
    status: 'read',
    type: 'inbox',
    stared: true,
    from: 'news@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055063,
    subject: 'Latest News and Updates',
    attach: [],
    body: 'Hello Jane, here are the latest news and updates from our company.',
    date: '2024-07-12',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'reminder@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055064,
    subject: 'Reminder: Upcoming Event',
    attach: [],
    body: 'Dear Jane Smith, just a reminder about the upcoming event this weekend.',
    date: '2024-07-13',
  },
  {
    userId: 4,
    status: 'read',
    type: 'inbox',
    stared: false,
    from: 'update@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055065,
    subject: 'System Update Notification',
    attach: [],
    body: 'Hi Jane, there is a scheduled system update on July 15th. Please prepare accordingly.',
    date: '2024-07-14',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: false,
    from: 'alert@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055066,
    subject: 'Security Alert',
    attach: [],
    body: 'Dear Jane Smith, we detected a suspicious login attempt on your account.',
    date: '2024-07-15',
  },
  {
    userId: 4,
    status: 'read',
    type: 'inbox',
    stared: false,
    from: 'info@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055067,
    subject: 'Information Update',
    attach: [],
    body: 'Hello Jane, we have updated our information. Check the details on our website.',
    date: '2024-07-16',
  },
  {
    userId: 4,
    status: 'unread',
    type: 'inbox',
    stared: true,
    from: 'event@example.com',
    to: 'me',
    img: 'static/img/users/4.png',
    id: 1585118055068,
    subject: 'Invitation to Exclusive Event',
    attach: [],
    body: 'Dear Jane Smith, you are invited to an exclusive event. Don’t miss out!',
    date: '2024-07-17',
  },
];
