export const columnDataCustomer = [
  { title: 'Common_STT', dataIndex: 'stt', key: 'stt' },
  { title: 'Customer_Code', dataIndex: 'code', key: 'code' },
  { title: 'Customer_Name', dataIndex: 'name', key: 'name' },
  { title: 'Common_Address', dataIndex: 'address', key: 'address' },
  { title: 'Common_Note', dataIndex: 'note', key: 'note' },
  { title: 'Common_TaxCode', dataIndex: 'tax_code', key: 'tax_code' },
  { title: 'Common_PhoneNumber', dataIndex: 'phone_number', key: 'phone_number' },
  { title: 'Common_NumOfDaysDebt', dataIndex: 'num_of_days_debt', key: 'num_of_days_debt' },
  { title: 'Common_MaxDebtAmount', dataIndex: 'max_debt_amount', key: 'max_debt_amount' },
  { title: 'Customer_AccountPayable', dataIndex: 'account_payable', key: 'account_payable' },
  { title: 'Common_ContactPersonTitle', dataIndex: 'contact_person_title', key: 'contact_person_title' },
  { title: 'Common_ContactPersonName', dataIndex: 'contact_person_name', key: 'contact_person_name' },
  {
    title: 'Common_ContactPersonPhoneNumber',
    dataIndex: 'contact_person_phone_number',
    key: 'contact_person_phone_number',
  },
  { title: 'Common_ContactPersonEmail', dataIndex: 'contact_person_email', key: 'contact_person_email' },
  { title: 'Common_DeliveryAddress', dataIndex: 'delivery_address', key: 'delivery_address' },
  { title: 'Common_Status', dataIndex: 'status', key: 'status' },
  { title: 'Common_CreatedAt', dataIndex: 'created_at', key: 'created_at' },
  { title: 'Common_UpdatedAt', dataIndex: 'updated_at', key: 'updated_at' },
  { title: 'Common_Action', dataIndex: 'action', key: 'action', width: '90px', fixed: 'right' },
];

export const fieldsModalCustomer = [
  { name: 'code', label: 'Customer_Code', type: 'input', required: true },
  { name: 'name', label: 'Customer_Name', type: 'input', required: true },
  { name: 'tax_code', label: 'Common_TaxCode', type: 'input', required: true },
  { name: 'address', label: 'Common_Address', type: 'input' },
  { name: 'phone_number', label: 'Common_PhoneNumber', type: 'input' },
  { name: 'num_of_days_debt', label: 'Common_NumOfDaysDebt', type: 'number' },
  { name: 'max_debt_amount', label: 'Common_MaxDebtAmount', type: 'number' },
  { name: 'account_payable', label: 'Customer_AccountPayable', type: 'number' },
  { name: 'contact_person_title', label: 'Common_ContactPersonTitle', type: 'input' },
  { name: 'contact_person_name', label: 'Common_ContactPersonName', type: 'input' },
  { name: 'contact_person_phone_number', label: 'Common_ContactPersonPhoneNumber', type: 'input' },
  { name: 'contact_person_email', label: 'Common_ContactPersonEmail', type: 'email' },
  { name: 'delivery_address', label: 'Common_DeliveryAddress', type: 'input' },
  {
    name: 'status',
    label: 'Common_Status',
    type: 'select',
    options: [
      { id: 1, name: 'Common_Using' },
      { id: 2, name: 'Common_NotUsing' },
    ],
  },
];
