export const columnDataProvider = [
  { title: 'Common_STT', dataIndex: 'stt', key: 'stt' },
  { title: 'Provider_Code', dataIndex: 'code', key: 'code' },
  { title: 'Provider_Name', dataIndex: 'name', key: 'name' },
  { title: 'Common_Address', dataIndex: 'address', key: 'address' },
  { title: 'Common_Note', dataIndex: 'note', key: 'note' },
  { title: 'Common_TaxCode', dataIndex: 'tax_code', key: 'tax_code' },
  { title: 'Common_PhoneNumber', dataIndex: 'phone_number', key: 'phone_number' },
  { title: 'Common_Website', dataIndex: 'website', key: 'website' },
  { title: 'Provider_IDNumber', dataIndex: 'id_number', key: 'id_number' },
  { title: 'Provider_IDIssueDay', dataIndex: 'id_issue_day', key: 'id_issue_day' },
  { title: 'Provider_IDIssueAddress', dataIndex: 'id_issue_address', key: 'id_issue_address' },
  { title: 'Provider_Term', dataIndex: 'term', key: 'term' },
  { title: 'Common_NumOfDaysDebt', dataIndex: 'num_of_days_debt', key: 'num_of_days_debt' },
  { title: 'Common_MaxDebtAmount', dataIndex: 'max_debt_amount', key: 'max_debt_amount' },
  { title: 'Provider_AccountPayable', dataIndex: 'account_payable', key: 'account_payable' },
  { title: 'Provider_Employee', dataIndex: 'employee', key: 'employee' },
  { title: 'Provider_EmployeeName', dataIndex: 'employee_name', key: 'employee_name' },
  { title: 'Provider_BankAccount', dataIndex: 'bank_account', key: 'bank_account' },
  { title: 'Provider_BankName', dataIndex: 'bank_name', key: 'bank_name' },
  { title: 'Provider_BankAccountBranch', dataIndex: 'bank_account_branch', key: 'bank_account_branch' },
  { title: 'Provider_BankAccountCity', dataIndex: 'bank_account_city', key: 'bank_account_city' },
  { title: 'Provider_Province', dataIndex: 'province', key: 'province' },
  { title: 'Provider_District', dataIndex: 'district', key: 'district' },
  { title: 'Provider_Ward', dataIndex: 'commune', key: 'commune' },
  { title: 'Common_ContactPersonTitle', dataIndex: 'contact_person_title', key: 'contact_person_title' },
  { title: 'Common_ContactPersonName', dataIndex: 'contact_person_name', key: 'contact_person_name' },
  {
    title: 'Common_ContactPersonPhoneNumber',
    dataIndex: 'contact_person_phone_number',
    key: 'contact_person_phone_number',
  },
  { title: 'Common_ContactPersonEmail', dataIndex: 'contact_person_email', key: 'contact_person_email' },
  { title: 'Provider_LegalRepresentative', dataIndex: 'legal_representative', key: 'legal_representative' },
  { title: 'Common_DeliveryAddress', dataIndex: 'delivery_address', key: 'delivery_address' },
  { title: 'Provider_IsIndividual', dataIndex: 'is_individual', key: 'is_individual' },
  { title: 'Provider_IsCustomer', dataIndex: 'is_customer', key: 'is_customer' },
  { title: 'Common_Status', dataIndex: 'status', key: 'status' },
  { title: 'Common_CreatedAt', dataIndex: 'created_at', key: 'created_at' },
  { title: 'Common_UpdatedAt', dataIndex: 'updated_at', key: 'updated_at' },
  { title: 'Common_Branch', dataIndex: 'branch', key: 'branch' },
  { title: 'Common_Action', dataIndex: 'action', key: 'action', width: '90px', fixed: 'right' },
];

export const fieldsModalProvider = [
  { name: 'code', label: 'Provider_Code', type: 'input', required: true },
  { name: 'name', label: 'Provider_Name', type: 'input', required: true },
  { name: 'tax_code', label: 'Common_TaxCode', type: 'input', required: true },
  { name: 'branch', label: 'Common_Branch', type: 'select', required: true },
  { name: 'address', label: 'Common_Address', type: 'input' },
  { name: 'phone_number', label: 'Common_PhoneNumber', type: 'input' },
  { name: 'website', label: 'Common_Website', type: 'input' },
  { name: 'id_number', label: 'Provider_IDNumber', type: 'input' },
  { name: 'id_issue_day', label: 'Provider_IDIssueDay', type: 'date' },
  { name: 'id_issue_address', label: 'Provider_IDIssueAddress', type: 'input' },
  { name: 'term', label: 'Provider_Term', type: 'input' },
  { name: 'num_of_days_debt', label: 'Common_NumOfDaysDebt', type: 'number' },
  { name: 'max_debt_amount', label: 'Common_MaxDebtAmount', type: 'number' },
  { name: 'account_payable', label: 'Provider_AccountPayable', type: 'number' },
  { name: 'employee', label: 'Provider_Employee', type: 'input' },
  { name: 'employee_name', label: 'Provider_EmployeeName', type: 'input' },
  { name: 'bank_account', label: 'Provider_BankAccount', type: 'input' },
  { name: 'bank_name', label: 'Provider_BankName', type: 'input' },
  { name: 'bank_account_branch', label: 'Provider_BankAccountBranch', type: 'input' },
  { name: 'bank_account_city', label: 'Provider_BankAccountCity', type: 'input' },
  { name: 'province', label: 'Provider_Province', type: 'select' },
  { name: 'district', label: 'Provider_District', type: 'select' },
  { name: 'commune', label: 'Provider_Ward', type: 'select' },
  { name: 'contact_person_title', label: 'Common_ContactPersonTitle', type: 'input' },
  { name: 'contact_person_name', label: 'Common_ContactPersonName', type: 'input' },
  { name: 'contact_person_phone_number', label: 'Common_ContactPersonPhoneNumber', type: 'input' },
  { name: 'contact_person_email', label: 'Common_ContactPersonEmail', type: 'email' },
  { name: 'legal_representative', label: 'Provider_LegalRepresentative', type: 'input' },
  { name: 'delivery_address', label: 'Common_DeliveryAddress', type: 'input' },
  {
    name: 'is_individual',
    label: 'Provider_IsIndividual',
    type: 'select',
    options: [
      { id: false, name: 'Common_Org' },
      { id: true, name: 'Common_Individual' },
    ],
  },
  { name: 'is_customer', label: 'Provider_IsCustomer', type: 'checkbox' },
  {
    name: 'status',
    label: 'Common_Status',
    type: 'select',
    options: [
      { id: 1, name: 'Common_Using' },
      { id: 2, name: 'Common_NotUsing' },
    ],
  },
];
